name: Check PDF Compilation

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: compile-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 'latest'

      - run: typst compile cv.typ --font-path ./src/fonts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./*.pdf
          if-no-files-found: error
